### ISSUE TITLE
Support Pihole-Exporter

### ISSUE THREAD

**Issue by onedr0p** [raspbernetes/multi-arch-images#10]
https://github.com/eko/pihole-exporter

**Comment by xUnholy** [comment]
It looks like it already supports multi-arch, was there a specific architecture you wanted?

https://github.com/eko/pihole-exporter/releases

**Comment by onedr0p** [comment]
The image isn't multi arch, the author is confused

**Comment by xUnholy** [comment]
Yep, they're just compiling the binary for multi architecture but not the docker image itself, I'll get my PR merged in then so we've got that also completed.

**Comment by onedr0p** [comment]
You should call the docker image `pihole-exporter` not just `pihole`

**Comment by xUnholy** [comment]
I'll have that corrected in the next pull request unless you beat me too it.

**Comment by onedr0p** [comment]
I still don't have access to create branches :(
