### ISSUE TITLE
/csi-node-driver-registrar: no such file or directory

### ISSUE THREAD

**Issue by UMB8998** [raspbernetes/multi-arch-images#112]
# Details

On the csi-node-driver-registrar, I can't start the container, on the event log it shows:

"RunContainerError: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/csi-node-driver-registrar\": stat /csi-node-driver-registrar: no such file or directory": unknown"

**What steps did you take and what happened:**

I have deployed the image inside a DaemonSet, on a amd64 machine (I also tried on a arm64 with the same error), if I use the quay.io image it work perfectly but I need it for a arm64 on which the quay doesn't work.

**What did you expect to happen:**

**Anything else you would like to add:**

This is part of the daemonset:

      - name: driver-registrar
        image: raspbernetes/csi-node-driver-registrar
        args:
        - --v=5
        - --csi-address=/csi-data/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/{{ .Values.csiDriver.name }}/csi.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /csi-data
          name: socket-dir
        - name: registration-dir
          mountPath: /registration

**Additional Information:**

I'm using K3S with Rancher, on a virtualized Ubuntu Server 20.4 machine (amd64) and Ubuntu Server 20.4 on a Raspberry Pi 4, I'm deploying the pod with Helm

P.S. sorry for my bad English

**Comment by xUnholy** [comment]
Hi @UMB8998, there was a change approx. 6days ago that might have caused this to occur, are you only experiencing it with this particular CSI image?

Could you possibly try using the following image variation and letting me know if it works for you. 

`raspbernetes/csi-node-driver-registrar:e4a67bc9c0f9aabf1d5614e6ac7afe34b5190db6`

**Comment by UMB8998** [comment]
Thank you for getting back to me, I was also experiencing that issue with:
csi-external-provisioner
csi-external-resizer
csi-external-snapshotter

using the image variation deployed without any issue, thanks

**Comment by xUnholy** [comment]
I found the issue and pushing a fix for it now, sorry about the inconvenience.

**Comment by xUnholy** [comment]
@UMB8998 before I merge this PR which should hopefully solve the issue can you try this image tag for me to validate it works. `a18dfca18a962d6c3b8a5ba4b0cb30820b00a5f2`

**Comment by UMB8998** [comment]
Of course, thank you for your help

**Comment by xUnholy** [comment]
> Of course, thank you for your help

I'll await your test 👍

**Comment by UMB8998** [comment]
Yes, it deployed without any issue, thank you

**Comment by xUnholy** [comment]
Once master has built the images you should be able to once again resume with the initial image tags

**Comment by UMB8998** [comment]
@xUnholy I have been trying the deployment, but I'm running into an issue, while the container deployed without any error, when I try to mount a volume in a pod it gives me a error that the CSI driver is not registered on the system, and in the logs, it shows: "Still connecting to unix:///csi-data/csi.sock"
When I look in the host in the registration path for the .sock file is not there, it seems like is there no connection back to the host. 
Trying on a amd64 system, with the quay.io image it works, but when I change to the multi-arch image the logs in the container show the same error, but i could mount the image because the driver file is still on the host.

**Comment by xUnholy** [comment]
That might be related to a user group issue that we merged this morning, can you try repull the images and set your image pull policy to always and try again to see if it works with the recently built images?

**Comment by UMB8998** [comment]
You are right, pulling the latest image solved the issue, thank you very much
