### ISSUE TITLE
Word of thanks

### ISSUE THREAD

**Issue by jaredallard** [raspbernetes/multi-arch-images#116]
Hey, just wanted to leave a generic "issue" here, thanks for doing all of this!

I didn't see this... sadly... and end up making my own awhile back: https://github.com/jaredallard-home/multiarch-images

Using some of the flux images here now and thank god someone else feels the pain of not having multiarch images, and with actual tags and not different images... Anyways, LMK if any of the work I did can be useful (flannel/logdna-agent). Will add future images I need as PRs here (if upstream doesn't support it). Thanks again for all of this work! :rocket:

**Comment by xUnholy** [comment]
Welcome, @jaredallard! 

Yep, definitely felt the pain when I began to realize a lack of support for multi-arch images across the Kubernetes ecosystem. Slowly we've been promoting these changes upstream which has been fantastic, we just use this as a place to maintain support until the upstreams provide official support.

I'd definitely love to see the images you've worked hard on contributed. Look forward to seeing your PR's and don't forget to join the community on slack 👍

**Comment by xUnholy** [comment]
Closing issue - look forward to your contributions!
