### ISSUE TITLE
cluster-autoscaler ARM64 support

### ISSUE THREAD

**Issue by arashkaffamanesh** [raspbernetes/multi-arch-images#135]
# Details

**Describe the solution you'd like:**

The cluster-autoscaler from here:
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
doesn't work on ARM, since the image is built for AMD64.

**Anything else you would like to add:**

The based image used is the distroless image which is apparently not ARM compatible.
Tried to use arm64v8/amazonlinux as the base image, without any luck.

**Additional Information:**

Not succeeded yet to build the ARM / multi-arch cluster-autoscaler image.

Create an issue as well here for EKS on ARM support:

https://github.com/aws/containers-roadmap/issues/1022

**Comment by xUnholy** [comment]
ARM64 image: `raspbernetes/cluster-autoscaler:cluster-autoscaler-chart-1.0.1` enjoy 👍
