### ISSUE TITLE
raspbernetes/csi-external-provisioner v2.0.0 crashes on kubernetes v1.19 exec format error.

### ISSUE THREAD

**Issue by Trackhe** [raspbernetes/multi-arch-images#144]
# Details
run kubernetes on rpi 64bit ubuntu 20.04

exec format error.
i always tried to pull arm64 img but everytime that error. version 1.6.0 is already working.

**Comment by xUnholy** [comment]
@Trackhe confirming v1.6.0 works however, v2.0.0 doesn't? The Kubernetes version shouldn't matter here; `exec format error` is due to architecture not being supported, I'll check if anything has changed.

**Comment by xUnholy** [comment]
Looks like their Makefile now handles the GOOS and GOARCH https://github.com/kubernetes-csi/external-provisioner/blob/c47eb1d05e417168765bbb545696176286800f90/release-tools/build.make#L74 and we need to set this correctly in our implementation

**Comment by xUnholy** [comment]
Feel free to use this bugfix branch, tried giving it a quick shot, which didn't work the first time around.

**Comment by Trackhe** [comment]
The Problem is now also for csi-attacher and longhorn-csi-plugin (raspbernetes/csi-node-driver-registrar)

**Comment by xUnholy** [comment]
@jamesorlakin looks like they changed the upstream Makefiles for the CSI images, it looked like they support `buildx` but in the quay repository they were just their standard amd64 interestingly.

**Comment by d7volker** [comment]
I experienced the same issue:

```
# lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
[..]
```

```
# podman pull --override-arch=arm64 raspbernetes/csi-external-provisioner:latest
Trying to pull docker.io/raspbernetes/csi-external-provisioner:latest...
Getting image source signatures
Copying blob 4000adbbc3eb skipped: already exists  
Copying blob 3c2cba919283 skipped: already exists  
Copying blob ee75c8894bd0 [--------------------------------------] 0.0b / 0.0b
Copying config 2861211da3 done  
Writing manifest to image destination
Storing signatures
2861211da3d85144baf03ad46a986b76bca655092c5c8999ba5b9524a8db317b
```

# podman run -it 2861211da3d8             
standard_init_linux.go:219: exec user process caused: exec format error

**Comment by jamesorlakin** [comment]
@xUnholy strange. I'll likely have time to look at the weekend. My original Ceph and K8s use-case wasn't very stable on 2GB Pis so I haven't touched it in a while!
