### ISSUE TITLE
kubernetes_incubator / nfs-provisioner multi-arch for longhorn nfs rwx.

### ISSUE THREAD

**Issue by Trackhe** [raspbernetes/multi-arch-images#146]
i need kubernetes_incubator / nfs-provisioner for longhorn nfs rwx and i guess any other need it too.

Longhorn use it in - https://longhorn.io/docs/1.0.2/advanced-resources/rwx-workloads/
I don't find actually the repo only - https://github.com/kubernetes/community/blob/master/incubator.md
Maybe any one entered already Incubation so is it maybe possible to build an arm64 image of that provisioner?!

Best Regards M.N.(Trackhe)

link another request to solve the problem - https://github.com/longhorn/longhorn/issues/1752

**Comment by crutonjohn** [comment]
I did find https://github.com/kubernetes-retired/external-storage/blob/master/nfs-client/docker/arm/Dockerfile but the repo is archived. I'm not really sure where the Dockerfile is built and pushed from exactly.

**Comment by crutonjohn** [comment]
https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/nfs

**Comment by xUnholy** [comment]
Another longhorn request here: #98

**Comment by Trackhe** [comment]
> Another longhorn request here: #98 

But your images support longhorn on rpi already.

**Comment by joshimoo** [comment]
The repro is here: https://github.com/kubernetes-retired/external-storage/tree/master/nfs/deploy/docker
There is an arm docker file: https://github.com/kubernetes-retired/external-storage/blob/master/nfs/deploy/docker/arm/Dockerfile

Linking to longhorn arm support issue longhorn/longhorn#6

**Comment by Trackhe** [comment]
https://hub.docker.com/repository/docker/trackhe/nfs-provisioner-arm
