### ISSUE TITLE
Silly Question, how to pull images correctly for Rook operator.yaml

### ISSUE THREAD

**Issue by matthew-williams** [raspbernetes/multi-arch-images#147]
I am sure this is simple, but I cannot see any consistency between peoples operator.yaml file and how to use the images you provide in mine.

Per this issue: [https://github.com/rook/rook/issues/5799](https://github.com/rook/rook/issues/5799)

He goes from `quay.io/k8scsi/csi-attacher` which totally resolves to a repo in my browser to `docker.io/madhupr001/csi-attacher` which does not but according to his comments thats not his issue (it's unrelated to his format of the url).

Now it looks like everything is supposed to be URL encoded for these ENV's but I have tried many versions for yours and cannot get anything except an image pull back off error.

I have tried the following formats:
`raspbernetes/ceph-csi`
`hub.docker.com/raspbernetes/ceph-csi`
`docker.io/raspbernetes/ceph-csi`

My current chunk is below:
```
# (Optional) Allow starting unsupported ceph-csi image
  ROOK_CSI_ALLOW_UNSUPPORTED_VERSION: "false"
  # The default version of CSI supported by Rook will be started. To change the version
  # of the CSI driver to something other than what is officially supported, change
  # these images to the desired release of the CSI driver.
  ROOK_CSI_CEPH_IMAGE: "docker.io/raspbernetes/ceph-csi"
  ROOK_CSI_REGISTRAR_IMAGE: "docker.io/raspbernetes/csi-node-driver-registrar"
  ROOK_CSI_RESIZER_IMAGE: "docker.io/raspbernetes/csi-external-resizer"
  ROOK_CSI_PROVISIONER_IMAGE: "docker.io/raspbernetes/csi-external-provisioner"
  ROOK_CSI_SNAPSHOTTER_IMAGE: "docker.io/raspbernetes/csi-external-snapshotter"
  ROOK_CSI_ATTACHER_IMAGE: "docker.io/raspbernetes/csi-external-attacher"
```

Any help would be appreciated. I have looked for a few hours and have not found any operator.yaml files that reference your images directly.

Thank you!

**Comment by xUnholy** [comment]
@matthew-williams not a silly question at all; I'm unfamiliar with the operator yaml you're referencing as I personally use OpenEBS, however, docker should be able to pull from the registry and with the following `docker pull raspbernetes/ceph-csi:v3.1.0-arm64` which was an example directly from dockerhub.

With the other images do they work correctly as expected?

If you could provide your error here that would be perfect!

**Comment by xUnholy** [comment]
Please take a look at dockerhub to find the correct tags to use, these ones you're showing do not exist. there doesn't need to be a suffix `-arm64`.
