### ISSUE TITLE
csi-external-attacher: exec format error

### ISSUE THREAD

**Issue by d7volker** [raspbernetes/multi-arch-images#166]
# Details

**What steps did you take and what happened:**

During deployment of kadalu, which makes use of the csi-external-attacher, to my raspberry pi cluster the following error appeared:

`standard_init_linux.go:211: exec user process caused "exec format error"`

I guess, this is related to the same issue, with csi-provisioner, mentioned here: #144, #154

**What did you expect to happen:**

I could prepare a pull request, but I am unable to test it.

**Comment by xUnholy** [comment]
@d7volker; @jamesorlakin is the best person who might be able to help - unless you're able to use his example to fix the provisioner image?

**Comment by jamesorlakin** [comment]
The build scripts appear to have changed in V3.0.0 of this plugin in a similar way to the others. I'll introduce a similar patch.

**Comment by d7volker** [comment]
@jamesorlakin : Thanks! I will test it as soon as possible.

**Comment by xUnholy** [comment]
@d7volker the new image should be available if you can please confirm, if it's not working we can re-open this ticket 🙏

**Comment by d7volker** [comment]
@xUnholy, @jamesorlakin : Thanks, I proofed the module to be working on my raspberry cluster!
But I have the same problem with another module. I am going to open a bug for it.
