### ISSUE TITLE
csi-node-driver-registrar: exec format error

### ISSUE THREAD

**Issue by d7volker** [raspbernetes/multi-arch-images#168]
# Details

**What steps did you take and what happened:**

During deployment of kadalu, which makes use of the csi-node-driver-registrar, to my raspberry pi cluster the following error appeared:

`standard_init_linux.go:211: exec user process caused "exec format error"`

I guess, this is related to the same issue, with csi-external-attacher, mentioned here: #166
Makefile issue

**Comment by jamesorlakin** [comment]
I'll have another look, I'm assuming it'll be the similar Makefile issue as on the other new CSI images.

**Comment by d7volker** [comment]
@jamesorlakin: Thank you! It worked :)
