### ISSUE TITLE
Add support for Fluxv2

### ISSUE THREAD

**Issue by anthr76** [raspbernetes/multi-arch-images#185]
# Details

**Describe the solution you'd like:** Multi-arch images for Fluxv2. Currently flux only offers a multi-arch variation for Armv7 and Arm64.

This issue will serve as tracking to get the Fluxv2 image(s) multi-arch. Feasibility and progress can be tracked here. I personally will be exploring this week.

**Comment by anthr76** [comment]
Fluxv2 images are hosted on GHCR and can be found here 

https://github.com/orgs/fluxcd/packages

**Comment by xUnholy** [comment]
Flux images are now multi-arch by default thanks to some of their latest releases where they were able to get architecture-specific pull data. Closing this ticket as it's now officially supported in the upstream 🎉
