### ISSUE TITLE
csi-external-snapshotter missing versions 3.0.3 and 4.0.0, latest downgraded to 2.1.4

### ISSUE THREAD

**Issue by zamnuts** [raspbernetes/multi-arch-images#207]
# Details

**What steps did you take and what happened:**

Image versions listed for `csi-external-snapshotter` are missing `3.0.3` and `4.0.0` on [docker hub raspbernetes/csi-external-snapshotter](https://hub.docker.com/r/raspbernetes/csi-external-snapshotter/tags?page=1&ordering=last_updated).

However, versions `3.0.0` (oldest 3.x) and `2.1.4` (latest 2.x) do exist on docker hub.

Additionally, `latest` points to `2.1.4`. Upon updating, should this point to `3.0.3`, `4.0.0` or the latest 2.x stable (`2.1.4`)? PR #206 fixed the build for csi-external-snapshotter (see #205), but accidentally made version `2.1.4` aliased by `latest`, despite `3.0.0` being the previous `latest`. This will cause a _downgrade_ on subsequent pulls for those using the `latest` tag.

**What did you expect to happen:**

Versions 3.0.3 and 4.0.0 should be made available, and _maybe_ `latest` should alias `4.0.0`.

**Additional Information:**

In what **order** should the [`.version` file](https://github.com/raspbernetes/multi-arch-images/blob/master/build/csi-external-snapshotter/.version) be updated?

**Comment by xUnholy** [comment]
There is an auto update workflow that should kickoff, if we want we can manually push to each version in the .version to have it built and pushed respectively.

**Comment by zamnuts** [comment]
I'm only able to find the [scheduler workflow which runs 10am daily](https://github.com/raspbernetes/multi-arch-images/blob/21c7284cf17adbdea6bb4ed4af81997eb2454018/.github/workflows/schedule.yml#L10).

Only the [latest version is considered](https://github.com/raspbernetes/multi-arch-images/blob/21c7284cf17adbdea6bb4ed4af81997eb2454018/.github/workflows/schedule.yml#L55-L58), which means we'll lose already released versions, and have to wait for the upstream to push first.

I vote we manually push each version:
1. `3.0.3` (ignoring 3.0.1 and 3.0.2)
2. `4.0.0`, which will also become `latest`

**Comment by zamnuts** [comment]
Thanks @xUnholy, I see the new ones published to hub, and was able to pull and run them on a handful of rk3399 cpus :+1:

**Comment by xUnholy** [comment]
Brilliant that is great news, once again thank you for the great contributions!
