### ISSUE TITLE
arm64 flux image not working

### ISSUE THREAD

**Issue by HaveFun83** [raspbernetes/multi-arch-images#39]
Hi thanks for your hard work on multiarch images for several projects.

I tried to use the raspbernetes/flux:1.18.0 on pi4 arm64 but pod crashloop with error
`standard_init_linux.go:211: exec user process caused "exec format error"`

Can you check the build process?

**Comment by onedr0p** [comment]
Interesting, can you post the output of `docker info` and `uname -a` ?

**Comment by likamrat** [comment]
I can confirm not working on pi3 as well:

standard_init_linux.go:211: exec user process caused "exec format error"

uname -a:
4.19.81-v7+ #1276 SMP Fri Nov 1 14:13:14 GMT 2019 armv7l GNU/Linux

**Comment by onedr0p** [comment]
This is also an issue with other Docker images as verified in Discord by @likamrat

**Comment by onedr0p** [comment]
I am pretty confident that the issue is we were using `BUILDPLATFORM` instead of `TARGETPLATFORM` in the FROM

See here:
https://github.com/raspbernetes/multi-arch-images/commit/6181db48c1322bcc063462c95525dc2adc211a85

**Comment by HaveFun83** [comment]
> Interesting, can you post the output of `docker info` and `uname -a` ?
> 
> @xUnholy maybe something got fudged with the builds?

uname -a
`5.3.0-1018-raspi2 #20~18.04.1-Ubuntu SMP Wed Feb 5 04:56:34 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

running k3s with containerd
```
Client:
  Version:  v1.3.3-k3s1
  Revision: 

Server:
  Version:  v1.3.3-k3s1
  Revision: 
  UUID: 61eae5ea-fe7d-48f7-b3b3-cdf51e456b31
```

**Comment by onedr0p** [comment]
@HaveFun83 and @likamrat please test the new image.

Make sure you pull the latest changes first:

`docker pull raspbernetes/flux:1.18.0`

Then you can try to see if you get the `exec error`

`docker run raspbernetes/flux:1.18.0 /usr/local/bin/fluxd`

**Comment by HaveFun83** [comment]
> @HaveFun83 and @likamrat please test the new image.
> 
> Make sure you pull the latest changes first:
> 
> `docker pull raspbernetes/flux:1.18.0`
> 
> Then you can try to see if you get the `exec error`
> 
> `docker run raspbernetes/flux:1.18.0 /usr/local/bin/fluxd`

:tada: removed the image from k3s and redeployed flux. 
Now the image is working on arm64

Thanks a lot guys
