### ISSUE TITLE
Build order for flux and pin versions for kustomize and sops

### ISSUE THREAD

**Issue by onedr0p** [raspbernetes/multi-arch-images#45]
I wonder if there's a way to set an order to build flux last as it depends on kustomize and sops.

Also might be wise to pin kustomize and sops versions in flux dockerfile instead of using latest.

**Comment by onedr0p** [comment]
For automation sale, it may be better to pull the version file for each from

https://github.com/fluxcd/flux/tree/master/docker

Same could be applied for helm-operator too.

**Comment by xUnholy** [comment]
Should be able to trigger separate workflows as dependencies to Flux: https://github.community/t5/GitHub-Actions/the-same-dependency-in-all-workflows-jobs/m-p/37367#M2904

I would keep them how they're but for the particular builds we should publish the versions and for latest and the dependent versions if possible.

**Comment by onedr0p** [comment]
Need to think of a way to get these in the COPY command of the flux dockerfile

- https://github.com/fluxcd/flux/blob/master/docker/kubectl.version
- https://github.com/fluxcd/flux/blob/master/docker/kustomize.version
- https://github.com/fluxcd/flux/blob/master/docker/sops.version

**Comment by onedr0p** [comment]
There's a small issue with `COPY --from` that doesn't allow you to use variables in that directive.

https://github.com/moby/moby/issues/34482

@xUnholy looks like we may need to host the binaries for kustomize and sops somewhere and pull those in with curl.

Any thoughts on what we could use for hosting static binaries?

**Comment by ikaruswill** [comment]
Hey guys, I came from the fluxcd thread, good to finally meet some people who work on kubernetes on the Pi. I have a cluster of 7 Pi3B+, 1 Pi4B+4G, 5Pi1B+ running K3s with fluxcd.

I have an automated image builder cicd pipeline that builds the sops and kustomize binaries in a multi-stage build. This ensures ordering but of course lengthens the build
If you're keen, I can submit a PR.

**Comment by ikaruswill** [comment]
As for hosting static binaries, I'm thinking we can setup one repository for each component here instead of a monorepo like this, which will allow for using Github releases for hosting.

**Comment by xUnholy** [comment]
@ikaruswill would love to see your repo where you've built your flux image, we've currently also got it building and tracking with the upstream release, however, we want to maintain pinning the version matrix to the matrix the upstream issue and not need to manually configure this each time they upgrade. Happy to take a pull request with improvements.

We're currently pushing all our images to docker.io which has been fantastic for us, is there any benefits to the Github release hosting in this context? It might be worth capturing that into another issue, as of yet mono repo has not been an issue.

**Comment by ikaruswill** [comment]
@xUnholy I currently keep a fork of fluxcd with my arm docker image file in a branch. I run the GithubApp [wei/pull](https://github.com/wei/pull) to keep the fork synced with upstream by polling at an interval, opening a PR, auto-merging and doing hardresets.

On premise, I run a Drone CI pipeline that listens for push webhooks from my flux fork (triggered by the hardresets), and do a git tag pull and push to trigger tag webhooks (So we don't always build on every commit)

This then triggers another Drone CI pipeline that checks out my arm branch, merges the tag commit in, and builds with the same files (sops, kustomize, kubernetes versions) as the ones used in the official docker build process.

The build is a multi-stage, building fluxd, kustomize, sops and downloading fluxctl and kubectl after which the build artifacts are copied into the final image based off alpine 3:10.

You can find my branch [here](https://github.com/ikaruswill/flux/tree/ikaruswill/arm-docker). All in all, I'd love to join you guys on this.

**Comment by ikaruswill** [comment]
@xUnholy On the Github release point. We can push just the binaries to Github release, and image building will be easier without having to deal with `COPY --from` variable substitution.

So if we wanted sops version 3.5.0, we just have to do a 
`curl -L https://github.com/raspbernetes/sops/releases/download/${SOPS_VERSION}/sops-v3.5.0.linux.arm`
Much akin to how mozilla sops publishes their [binaries](https://github.com/mozilla/sops/releases)

**Comment by xUnholy** [comment]
Interesting, I've not seen the wei/pull Github app, we were able to achieve the same result through Github actions, we only pull the latest releases (not pulling on each commit). 

The main concept behind this particular repository was to have a place where the community could request different architecture support, although ultimately the objective is to get these changes reflected in the upstream maintainers.

Using Github releases I don't think would be an issue in regards to artifact management, like we're currently doing we can have custom workflows suited for specific directory structures and tagging to suffice. I do like the idea of storing the binary because of the ability to then reference the version as a build arg.

We've got a great community of individuals, come to join us on discord: https://discord.gg/RGvKzVg

**Comment by onedr0p** [comment]
@ikaruswill please feel free to open a PR with any proposed changes, we'd love the help :)

**Comment by xUnholy** [comment]
**Allow to use environment variables in COPY --from
https://github.com/moby/moby/issues/34482

**Comment by RobReus** [comment]
I just created PR #115 which introduces using a build stage for fluxd. We could also add the building of `kustomize` and `sops` into this same stage. It will however increase the build time.

I would prefer the solution @ikaruswill mentioned about releasing the binary builds for them to github. We can then easily dynamically fetch the correct version during `flux` image building using the version files inside the fluxcd repo.

**Comment by xUnholy** [comment]
Flux is now in maintenance mode and fluxv2 has support for separate architectures using the `--arch` flag (although they don't support multi-arch images) so you can target a particular architecture. I will close this issue and recommend everyone to consider moving towards using the new flux as again this is no longer receiving updates upstream.
