### ISSUE TITLE
support istio multi-architecture docker images

### ISSUE THREAD

**Issue by xUnholy** [raspbernetes/multi-arch-images#5]
Compile the latest version of Istio components to be compatible with ARM / ARM64 / AMD64 architecture.

Components:
- pilot 
- proxyv2 
- app 
- app_sidecar 
- test_policybackend 
- mixer 
- mixer_codegen 
- citadel 
- galley 
- sidecar_injector 
- kubectl  [CONFIRM?]
- istioctl [CONFIRM?]
- operator

**Comment by xUnholy** [comment]
Istio has released v1.5 this would be an ideal position to begin making multiple architecture available as the control plane has been reduced into a monolithic app called Istiod.

Raised another issue to track envoy support.

**Comment by xUnholy** [comment]
https://github.com/istio/istio/issues/21094

**Comment by MrXinWang** [comment]
@xUnholy I think this multi-architechture docker image supporting makes a lot of sense :)) As not only istio itself is a very important and popular project, and also a lot of other k8s-based project, such as the [kubeflow](https://www.kubeflow.org/docs/started/k8s/kfctl-k8s-istio/) project, uses istio too.

Probably we can start from arm64 architecture? If so, maybe we can work on PRs and docker manifests to the community?

**Comment by xUnholy** [comment]
@MrXinWang I've managed to build all the Istio images into arm architecture.

However, I need to get around to compiling envoy to arm as that is the last dependency to get working for arm before I believe we'll have Istio working end to end, I'll also publish my images publically once we've got working e2e.

If you wanna help and/or test what I've currently done, join our discord and reach out, happy to consider a nice approach to support the community with arm versions as mentioned in the Istio thread.

**Comment by MrXinWang** [comment]
@xUnholy Thanks for the reply, I checked with some of my colleagues, I think envoy supports arm64 now?

**Comment by xUnholy** [comment]
I'm compiling to be compatible with all the following architectures: ARM / ARM64 and AMD64

If we can confirm these are all supported that would be fantastic!

**Comment by xUnholy** [comment]
Opened specific issue to track Envoy issues: https://github.com/raspbernetes/multi-arch-images/issues/55

**Comment by morlay** [comment]
related https://github.com/istio/istio/issues/21094#issuecomment-642363692

@xUnholy tracking here?

Actions: 

[ ] istio-envoy (envoy-wasm)  
    [ ] `gn` for arm/v7. need help from https://github.com/Jingzhao123/google-gn/issues/1
    [ ] istio-enovy-build-env. could fork from https://github.com/morlay/istio-proxy-build-env/tree/build-env
[ ] istio binaries build https://github.com/istio/istio/pull/24594
[ ] istio oci images build

**Comment by xUnholy** [comment]
Yeah we can track here is fine 👍 

Feel free to join for a chat over discord too https://discord.gg/RGvKzVg

**Comment by morlay** [comment]
see all in one https://github.com/querycap/istio

**Comment by xUnholy** [comment]
Closing this issue as images are now supported.

**Comment by ReOneK** [comment]
So,here is the arm64 arch for envoy has been completed?
