### ISSUE TITLE
arm64 flux kubeyaml issue

### ISSUE THREAD

**Issue by HaveFun83** [raspbernetes/multi-arch-images#56]
Hi
looks like the kubeyaml image referenced in flux dockerfile can not run on arm64
https://github.com/raspbernetes/multi-arch-images/blob/78b3faaac4a36fc3e80619da15d1608bdf7616f8/build/flux/Dockerfile#L46

after i applied a helmrelease which should be automated by flux i get the following issues within the flux log.
```
gitops/flux-c55549f45-2jct2[flux]: ts=2020-03-14T23:02:45.336631844Z caller=loop.go:151 component=sync-loop jobID=465e0132-22fe-9a78-4aa9-91285f059732 state=done success=false err="applying changes: updating resource monitoring:helmrelease/infra-grafana in fluxcd/monitoring/grafana/infra-grafana_hr.yaml: fork/exec /usr/lib/kubeyaml/kubeyaml: exec format error"
```
and flux is unable to upgrade the helmrelease to a newer image.

Can you check included image?

Thanks in advance

**Comment by xUnholy** [comment]
It looks like the upstream isn't supporting multi-image architecture, we can most certainly do this in our repository and manage releases against the upstream repository.

I've raised a new issue to track kubeyaml being supported into this repository - #57 

If you'd like to contribute and raise a PR for kubeyaml into this repository that would be awesome.

**Comment by HaveFun83** [comment]
@xUnholy can you fix the flux dockerfile with the new kubeyaml ref or should i open a new pr?

**Comment by xUnholy** [comment]
@HaveFun83 happy for you to make another PR with the changes 👍
