### ISSUE TITLE
Support Velero Plugin for AWS

### ISSUE THREAD

**Issue by onedr0p** [raspbernetes/multi-arch-images#7]
My repos can be migrated over:
- https://gitlab.com/onedr0p/velero
- https://gitlab.com/onedr0p/velero-plugin-for-aws

**Comment by xUnholy** [comment]
@onedr0p Velero already seems to support ARM - was there an issue you had with their official image?

**Comment by onedr0p** [comment]
That's awesome! I didn't catch that. 

The aws plugin however is not multi arch.

https://github.com/vmware-tanzu/velero-plugin-for-aws/issues/18
