### ISSUE TITLE
prometheus-operator helm chart

### ISSUE THREAD

**Issue by xUnholy** [raspbernetes/multi-arch-images#71]
https://github.com/raspbernetes/multi-arch-images/pull/64

The prometheus-operator helm chart bundles several tools as part of the deployment and these also need to be multi-arch compatible.

The currently identified images are below:

- squareup/ghostunnel:v1.5.2
- quay.io/coreos/kube-state-metrics:v1.9.5
- kiwigrid/k8s-sidecar:0.1.99

**Comment by stefancrain** [comment]
kiwigrid/k8s-sidecar does not have `0.1.99` published [as a release ](https://github.com/kiwigrid/k8s-sidecar/releases), so I've started with `0.1.110`

**Comment by xUnholy** [comment]
@stefancrain yep sounds good! In the issue linked just recently, I think we still have 2 images and we should have all things covered.
