### ISSUE TITLE
Add Support for rancher/longhorn

### ISSUE THREAD

**Issue by HaveFun83** [raspbernetes/multi-arch-images#98]
Will be great to see multiarch images for [rancher/longhorn](https://github.com/longhorn/longhorn) 

There is an open issue but currently no progress https://github.com/longhorn/longhorn/issues/6

thanks in advance

**Comment by vanakema** [comment]
+1

**Comment by Trackhe** [comment]
You can use longhorn on kubernetes rpi with 
```
sudo snap install helm --classic && \
git clone https://github.com/longhorn/longhorn.git && \
cd longhorn/chart/ && \
rm values.yaml && \
wget https://raw.githubusercontent.com/Trackhe/Raspberry64bitKubernetesServerDualstack/master/deployment/values.yaml && \
kubectl create namespace longhorn-system && \
helm install longhorn . --namespace longhorn-system
```

**Comment by HaveFun83** [comment]
longhorn support arm64 since version v1.1.0 
https://github.com/longhorn/longhorn/releases/tag/v1.1.0

close this now
